import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar_2 from "./components/Landing/navbar_2";
import Footer_1 from "./components/Landing/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BLACKDICE SHOPPING MART",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-screen items-center justify-center flex flex-col bg-main-100`}
      >
        <Navbar_2 />
        {children}
        <Footer_1 />
      </body>
    </html>
  );
}
